// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetApp = `-- name: GetApp :one
SELECT id, name, description, created_at, updated_at FROM apps
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetApp(ctx context.Context, id pgtype.UUID) (App, error) {
	row := q.db.QueryRow(ctx, GetApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
