// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID      `json:"id"`
	SessionID pgtype.UUID      `json:"session_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	Revoked   *bool            `json:"revoked"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Role struct {
	ID        pgtype.UUID      `json:"id"`
	AppID     pgtype.UUID      `json:"app_id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	DeviceInfo *string          `json:"device_info"`
	IpAddress  *string          `json:"ip_address"`
	Revoked    *bool            `json:"revoked"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
}

type User struct {
	ID            pgtype.UUID      `json:"id"`
	AppID         pgtype.UUID      `json:"app_id"`
	Email         string           `json:"email"`
	PasswordHash  string           `json:"password_hash"`
	IsActive      *bool            `json:"is_active"`
	EmailVerified *bool            `json:"email_verified"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type UserRole struct {
	UserID     pgtype.UUID      `json:"user_id"`
	RoleID     pgtype.UUID      `json:"role_id"`
	AssignedAt pgtype.Timestamp `json:"assigned_at"`
}
