// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error
	FindRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRolesForUser(ctx context.Context, userID pgtype.UUID) ([]Role, error)
	GetSessionsForUser(ctx context.Context, userID pgtype.UUID) ([]Session, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByAppAndEmail(ctx context.Context, arg GetUserByAppAndEmailParams) (User, error)
	GetUserPasswordHash(ctx context.Context, id pgtype.UUID) (string, error)
	InsertUserRole(ctx context.Context, arg InsertUserRoleParams) (UserRole, error)
	RevokeAllRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) error
	RevokeAllSessionsForUser(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) (RefreshToken, error)
	RevokeRefreshTokensForSession(ctx context.Context, sessionID pgtype.UUID) error
	RevokeSession(ctx context.Context, id pgtype.UUID) (Session, error)
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (User, error)
	VerifySession(ctx context.Context, id pgtype.UUID) (Session, error)
	VerifySessionBelongsToUser(ctx context.Context, arg VerifySessionBelongsToUserParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
