// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (session_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, user_id, token_hash, revoked, expires_at, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	SessionID pgtype.UUID      `json:"session_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, CreateRefreshToken,
		arg.SessionID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.TokenHash,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const FindRefreshToken = `-- name: FindRefreshToken :one
SELECT id, session_id, user_id, token_hash, revoked, expires_at, created_at, updated_at FROM refresh_tokens
WHERE token_hash = $1
  AND revoked = FALSE
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) FindRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, FindRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.TokenHash,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const RevokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked = TRUE
WHERE user_id = $1
  AND revoked = FALSE
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, RevokeAllRefreshTokensForUser, userID)
	return err
}

const RevokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
SET revoked = TRUE
WHERE id = $1
RETURNING id, session_id, user_id, token_hash, revoked, expires_at, created_at, updated_at
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, RevokeRefreshToken, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.TokenHash,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const RevokeRefreshTokensForSession = `-- name: RevokeRefreshTokensForSession :exec
UPDATE refresh_tokens
SET revoked = TRUE
WHERE session_id = $1
  AND revoked = FALSE
`

func (q *Queries) RevokeRefreshTokensForSession(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, RevokeRefreshTokensForSession, sessionID)
	return err
}
