// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetRole = `-- name: GetRole :one
SELECT id, app_id, name, created_at, updated_at FROM roles
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRole(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, GetRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
