// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, device_info, ip_address, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, device_info, ip_address, revoked, created_at, updated_at, expires_at
`

type CreateSessionParams struct {
	UserID     pgtype.UUID      `json:"user_id"`
	DeviceInfo *string          `json:"device_info"`
	IpAddress  *string          `json:"ip_address"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, CreateSession,
		arg.UserID,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const GetSessionsForUser = `-- name: GetSessionsForUser :many
SELECT id, user_id, device_info, ip_address, revoked, created_at, updated_at, expires_at FROM sessions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetSessionsForUser(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, GetSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.Revoked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RevokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE sessions
SET revoked = TRUE
WHERE user_id = $1
  AND revoked = FALSE
`

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, RevokeAllSessionsForUser, userID)
	return err
}

const RevokeSession = `-- name: RevokeSession :one
UPDATE sessions
SET revoked = TRUE
WHERE id = $1
RETURNING id, user_id, device_info, ip_address, revoked, created_at, updated_at, expires_at
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, RevokeSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const VerifySession = `-- name: VerifySession :one
SELECT id, user_id, device_info, ip_address, revoked, created_at, updated_at, expires_at FROM sessions
WHERE id = $1
  AND revoked = FALSE
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) VerifySession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, VerifySession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const VerifySessionBelongsToUser = `-- name: VerifySessionBelongsToUser :one
SELECT id, user_id, device_info, ip_address, revoked, created_at, updated_at, expires_at FROM sessions
WHERE id = $1
  AND user_id = $2
LIMIT 1
`

type VerifySessionBelongsToUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) VerifySessionBelongsToUser(ctx context.Context, arg VerifySessionBelongsToUserParams) (Session, error) {
	row := q.db.QueryRow(ctx, VerifySessionBelongsToUser, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
