// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const DeleteUserRole = `-- name: DeleteUserRole :exec
DELETE FROM user_roles
WHERE user_id = $1
  AND role_id = $2
`

type DeleteUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error {
	_, err := q.db.Exec(ctx, DeleteUserRole, arg.UserID, arg.RoleID)
	return err
}

const GetRolesForUser = `-- name: GetRolesForUser :many
SELECT r.id, r.app_id, r.name, r.created_at, r.updated_at FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name
`

func (q *Queries) GetRolesForUser(ctx context.Context, userID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, GetRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserRole = `-- name: GetUserRole :one
SELECT user_id, role_id, assigned_at FROM user_roles
WHERE user_id = $1
  AND role_id = $2
LIMIT 1
`

type GetUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, GetUserRole, arg.UserID, arg.RoleID)
	var i UserRole
	err := row.Scan(&i.UserID, &i.RoleID, &i.AssignedAt)
	return i, err
}

const InsertUserRole = `-- name: InsertUserRole :one
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
RETURNING user_id, role_id, assigned_at
`

type InsertUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, InsertUserRole, arg.UserID, arg.RoleID)
	var i UserRole
	err := row.Scan(&i.UserID, &i.RoleID, &i.AssignedAt)
	return i, err
}
