// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (app_id, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, app_id, email, password_hash, is_active, email_verified, created_at, updated_at
`

type CreateUserParams struct {
	AppID        pgtype.UUID `json:"app_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser, arg.AppID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUser = `-- name: GetUser :one
SELECT id, app_id, email, password_hash, is_active, email_verified, created_at, updated_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, GetUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserByAppAndEmail = `-- name: GetUserByAppAndEmail :one
SELECT id, app_id, email, password_hash, is_active, email_verified, created_at, updated_at FROM users
WHERE app_id = $1
  AND email = $2
LIMIT 1
`

type GetUserByAppAndEmailParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Email string      `json:"email"`
}

func (q *Queries) GetUserByAppAndEmail(ctx context.Context, arg GetUserByAppAndEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByAppAndEmail, arg.AppID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, GetUserPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const UpdateUserPasswordHash = `-- name: UpdateUserPasswordHash :one
UPDATE users
SET password_hash = $2
WHERE id = $1
RETURNING id, app_id, email, password_hash, is_active, email_verified, created_at, updated_at
`

type UpdateUserPasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (User, error) {
	row := q.db.QueryRow(ctx, UpdateUserPasswordHash, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
